[package]
name = "triangles"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
triangulate = "0.2.0"
ordered-float = "3.7.0"
num-traits = "0.2.15"
log = "0.4.18"

[dev-dependencies]
svg = "0.13.1"